const $=id=>document.getElementById(id); let current=[];
const example=`position_nm,diameter_nm,region
-6700,250,Mirror
-6150,250,Mirror
-5600,250,Mirror
-2310,255,Taper
-1780,260,Taper
-1260,265,Taper
-750,270,Taper
-250,275,Central cavity`;
function parse(text){const lines=text.trim().split(/\r?\n/).filter(Boolean);if(!lines.length)return[];let start=/[a-zA-Z]/.test(lines[0].split(/[,\t]/)[0])?1:0;return lines.slice(start).map((line,i)=>{const p=line.split(/[,\t]/).map(x=>x.trim());const pos=Number(p[0]),dia=Number(p[1]);if(!Number.isFinite(pos)||!Number.isFinite(dia)||dia<=0)throw new Error(`Invalid numeric value on data row ${i+1}.`);return{pos,dia,region:p.slice(2).join(' ')||'—'}}).sort((a,b)=>a.pos-b.pos)}
function analyze(){try{const arr=parse($('patternInput').value);if(!arr.length)throw new Error('Paste at least one valid hole.');const minGap=Number($('minGap').value),maxStep=Number($('maxDiaStep').value);arr.forEach((h,i)=>{h.c2c=i? h.pos-arr[i-1].pos:null;h.gap=i? h.c2c-(h.dia+arr[i-1].dia)/2:null;h.flags=[];if(i&&h.c2c===0)h.flags.push('duplicate center');if(i&&h.gap<0)h.flags.push('overlap');else if(i&&h.gap<minGap)h.flags.push('gap below threshold');if(i&&Math.abs(h.dia-arr[i-1].dia)>maxStep)h.flags.push('diameter step');h.status=h.flags.some(x=>x==='overlap'||x==='duplicate center'||x==='gap below threshold')?'violation':h.flags.length?'review':'pass'});current=arr;render(arr);$('message').textContent='';$('exportCsv').disabled=false}catch(e){$('message').textContent=e.message}}
function fmt(v){return v==null?'—':Number(v.toFixed(3)).toString()}
function render(a){$('resultsBody').innerHTML=a.map((h,i)=>`<tr><td>${i+1}</td><td>${fmt(h.pos)}</td><td>${fmt(h.dia)}</td><td>${fmt(h.c2c)}</td><td>${fmt(h.gap)}</td><td>${esc(h.region)}</td><td><span class="status ${h.status}">${h.status==='pass'?'PASS':h.status==='review'?'REVIEW':'FLAG'}</span>${h.flags.length?` <small title="${esc(h.flags.join(', '))}">${esc(h.flags.join(', '))}</small>`:''}</td></tr>`).join('');$('mHoles').textContent=a.length;$('mSpan').textContent=a.length>1?`${fmt(a.at(-1).pos-a[0].pos)} nm`:'0 nm';const gaps=a.map(x=>x.gap).filter(x=>x!=null);$('mMinGap').textContent=gaps.length?`${fmt(Math.min(...gaps))} nm`:'—';$('mFlags').textContent=a.filter(x=>x.status!=='pass').length;draw(a)}
function draw(a){const c=$('patternCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fafbfc';ctx.fillRect(0,0,w,h);if(!a.length)return;const pad=70,min=a[0].pos,max=a.at(-1).pos,span=Math.max(1,max-min);const x=p=>pad+(p-min)/(span)*(w-2*pad);ctx.strokeStyle='#c7cdd2';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(pad,h/2);ctx.lineTo(w-pad,h/2);ctx.stroke();a.forEach((q,i)=>{const r=Math.max(7,Math.min(23,q.dia/14));ctx.beginPath();ctx.arc(x(q.pos),h/2,r,0,Math.PI*2);ctx.fillStyle=q.status==='violation'?'#b42318':q.status==='review'?'#a46b00':'#207a50';ctx.fill();ctx.fillStyle='#65717c';ctx.font='18px sans-serif';ctx.textAlign='center';ctx.fillText(String(i+1),x(q.pos),h/2+55);ctx.save();ctx.translate(x(q.pos),h/2-45);ctx.rotate(-Math.PI/4);ctx.textAlign='left';ctx.font='16px sans-serif';ctx.fillText(q.region,0,0);ctx.restore()})}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function exportCsv(){if(!current.length)return;const rows=[['index','position_nm','diameter_nm','c2c_prev_nm','edge_gap_nm','region','status','flags'],...current.map((h,i)=>[i+1,h.pos,h.dia,h.c2c??'',h.gap??'',h.region,h.status,h.flags.join('; ')])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='ebl_pattern_analysis.csv';a.click();URL.revokeObjectURL(u)}
$('analyze').onclick=analyze;$('loadExample').onclick=()=>{$('patternInput').value=example;analyze()};$('clear').onclick=()=>{$('patternInput').value='';current=[];$('exportCsv').disabled=true;$('resultsBody').innerHTML='<tr><td colspan="7" class="empty">Analyze a pattern to populate results.</td></tr>';['mHoles','mFlags'].forEach(id=>$(id).textContent='0');['mSpan','mMinGap'].forEach(id=>$(id).textContent='—');draw([])};$('exportCsv').onclick=exportCsv;draw([]);
